version: '3.8'

services:

  db:
    image: 'postgres:latest'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${PGRS_PASSWORD}
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres-network

volumes:
  postgres:
  pgadmin:

networks:
  postgres-network:
    driver: bridge

